name: flit
description: Universal package for quick time structured apps
version: 0.0.1
author: T Barker
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management with bloc
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  reactive_forms: ^10.2.0
  #dependancy injection
  get_it: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: